### PR TITLE
Notify panda of the node on which the wrapper is running

### PR DESCRIPTION
**Pull request by TimoWilken**
The request payload should mirror what the pilot is doing:

https://github.com/PanDAWMS/pilot3/blob/568c7fc508d33cceefbf7d414bb9bb664fd05043/pilot.py#L864 https://github.com/PanDAWMS/pilot3/commit/6ababd552b608469740f63a78c62e1671635bf9c

### CODE REVIEW

**Comment by TimoWilken** [comment]
Hi! This is more of a first attempt; reviews would be appreciated. Specifically:

1. I don't know if the right place to call the function is together with `apfmon_running`.
2. Maybe it's a good idea to extract the panda server URL -- it's hardcoded elsewhere in the script and I copied it from there. There's also the `--harvester` arg that sets `$pandaurl`, but that variable is never used...
3. I don't know what curl version we can expect, and whether it supports `--data-urlencode`.

**Comment by rodwalker** [comment]
I expect the status needs to be one known by panda/harvester as per harvester monit.
Use CVMFS_BASE in case it is no in the usual place.
Not sure about the port but could use the already set
pandaurl='https://pandaserver.cern.ch:25443' .... I agree with you on (2)

**Comment by TimoWilken** [comment]
Done, thanks @rodwalker!

**Comment by ptrlv** [comment]
Hi Timo, please send another PR with this but on 'next' branch. I don't see how to switch branches on this PR. Thanks!

**Pull request closed without merging**
